#pragma once

#ifndef __GAME_INPUT_H__
#define __GAME_INPUT_H__

enum GameInput
{
	INVALID_GAME_INPUT = -1,
	GAME_INPUT_UP,
	GAME_INPUT_DOWN,
	GAME_INPUT_LEFT,
	GAME_INPUT_RIGHT,
	GAME_INPUT_LIGHT,
	GAME_INPUT_MED,
	GAME_INPUT_HEAVY,
	GAME_INPUT_QCF,
	GAME_INPUT_QCB,
	GAME_INPUT_HCF,
	GAME_INPUT_HCB,
	GAME_INPUT_DRAGON_FIST,
	NUM_GAME_INPUTS
};

#endif